# Generated by Django 3.1.2 on 2020-12-23 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201222_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='another_user',
            field=models.ManyToManyField(blank=True, related_name='another_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
